// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2kXU-EVSLDOpabBGS1vICDR-BcW3VwXs',
    appId: '1:820114078330:web:fafe3bf66924040b0d99c3',
    messagingSenderId: '820114078330',
    projectId: 'pooplemah-91329',
    authDomain: 'pooplemah-91329.firebaseapp.com',
    storageBucket: 'pooplemah-91329.firebasestorage.app',
    measurementId: 'G-Z9RF84SR25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfPPGLxwg0CvRJIA2UXVdS2JQyJ4TFtxg',
    appId: '1:820114078330:android:1aa31e5876dc43fe0d99c3',
    messagingSenderId: '820114078330',
    projectId: 'pooplemah-91329',
    storageBucket: 'pooplemah-91329.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr2KbsmXjSZ2U0IFO1mQv6UxrGae5bKgw',
    appId: '1:820114078330:ios:55fdb09af05e520e0d99c3',
    messagingSenderId: '820114078330',
    projectId: 'pooplemah-91329',
    storageBucket: 'pooplemah-91329.firebasestorage.app',
    iosBundleId: 'com.example.mad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr2KbsmXjSZ2U0IFO1mQv6UxrGae5bKgw',
    appId: '1:820114078330:ios:55fdb09af05e520e0d99c3',
    messagingSenderId: '820114078330',
    projectId: 'pooplemah-91329',
    storageBucket: 'pooplemah-91329.firebasestorage.app',
    iosBundleId: 'com.example.mad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2kXU-EVSLDOpabBGS1vICDR-BcW3VwXs',
    appId: '1:820114078330:web:28a8d22d9016ad8f0d99c3',
    messagingSenderId: '820114078330',
    projectId: 'pooplemah-91329',
    authDomain: 'pooplemah-91329.firebaseapp.com',
    storageBucket: 'pooplemah-91329.firebasestorage.app',
    measurementId: 'G-5SP0Z2MMEX',
  );

}